# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [{ id = "trailing-whitespace" }, { id = "end-of-file-fixer" }, { id = "check-toml" }]

[[repos]]
repo = "local"
hooks = [
  { id = "fmt", name = "vp fmt", entry = "vp fmt", language = "system", pass_filenames = false, stages = [
    "pre-commit",
  ], priority = 0 },
  { id = "lint", name = "vp lint", entry = "vp lint", language = "system", pass_filenames = false, stages = [
    "pre-commit",
  ], priority = 10 },
  { id = "lint-devtools", name = "vp lint:devtools", entry = "vp run lint:devtools", language = "system", pass_filenames = false, stages = [
    "pre-commit",
  ], priority = 10 },
  { id = "typecheck", name = "vp typecheck", entry = "vp run typecheck", language = "system", pass_filenames = false, stages = [
    "pre-commit",
  ], priority = 10 },
  { id = "test", name = "vp test", entry = "vp run test", language = "system", pass_filenames = false, stages = [
    "pre-commit",
  ], priority = 20 },
]
