name: GitHub Pages Deploy

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
      - run: vp install --frozen-lockfile
      - run: vp build
      - name: Build devtools
        run: vp build --config devtools/vite.config.ts
      - name: Build typedoc
        run: vp run build:typedoc
      - name: copy
        run: |
          mkdir -p ./output/devtools
          cp -r ./typedoc ./output/typedoc
          cp -r ./devtools/dist/* ./output/devtools
          cp -r ./devtools/dist/assets ./output/devtools/assets
      - name: Upload files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: media-processors
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    needs: deploy_job
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
