name: e2e-test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
    # branches-ignore:
    #   - feature/react-zustand
  schedule:
    # UTC 時間で毎日 2:00 (JST で 11:00) に実行、月曜日から金曜日
    - cron: '0 2 * * 1-5'

jobs:
  e2e_test_job:
    strategy:
      matrix:
        node-version: ['20', '22', '23']
        # browser: ["chromium", "firefox", "webkit"]
        browser: ['chromium']
    env:
      VITE_AYAME_SIGNALING_URL: ${{ secrets.TEST_SIGNALING_URL }}
      VITE_AYAME_ROOM_ID_PREFIX: ${{ secrets.TEST_ROOM_ID_PREFIX }}
      VITE_AYAME_SIGNALING_KEY: ${{ secrets.TEST_SIGNALING_KEY }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm build
      - run: pnpm exec playwright install ${{ matrix.browser }} --with-deps
      - run: pnpm exec playwright test --project=${{ matrix.browser }}
        env:
          VITE_AYAME_ROOM_NAME: ${{ matrix.node-version }}
